////////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor -- see https://github.com/KeyWorksRW/wxUiEditor/
//
// DO NOT EDIT THIS FILE! Your changes will be lost if it is re-generated!
////////////////////////////////////////////////////////////////////////////////

#include <wx/button.h>
#include <wx/sizer.h>
#include <wx/stattext.h>

#include "convertvs_base.h"

bool ConvertVS::Create(wxWindow *parent, wxWindowID id, const wxString &title,
        const wxPoint&pos, const wxSize& size, long style, const wxString &name)
{
    if (!wxDialog::Create(parent, id, title, pos, size, style, name))
        return false;

    auto dlg_sizer = new wxBoxSizer(wxVERTICAL);

    auto box_sizer = new wxBoxSizer(wxHORIZONTAL);
    dlg_sizer->Add(box_sizer, wxSizerFlags().Border(wxALL));

    auto staticText_3 = new wxStaticText(this, wxID_ANY, "Specify the filename of the Visual Studio project file you wish to convert, and the CMake root directory where the CmakeLists.txt file should be created.");
    staticText_3->Wrap(350);
    box_sizer->Add(staticText_3, wxSizerFlags().Border(wxALL));

    auto flex_grid_sizer = new wxFlexGridSizer(2, 0, 0);
    dlg_sizer->Add(flex_grid_sizer, wxSizerFlags(1).Expand().Border(wxALL));

    auto staticText = new wxStaticText(this, wxID_ANY, "VS Project:");
    flex_grid_sizer->Add(staticText, wxSizerFlags().Center().Border(wxALL));

    m_filePicker = new wxFilePickerCtrl(this, wxID_ANY, wxEmptyString, wxFileSelectorPromptStr, wxFileSelectorDefaultWildcardStr, wxDefaultPosition, wxDefaultSize,
        wxFLP_USE_TEXTCTRL|wxFLP_OPEN|wxFLP_FILE_MUST_EXIST);
    m_filePicker->SetMinSize(wxSize(250, -1));
    flex_grid_sizer->Add(m_filePicker, wxSizerFlags().Border(wxALL));

    auto staticText_2 = new wxStaticText(this, wxID_ANY, "CMake Root:");
    flex_grid_sizer->Add(staticText_2, wxSizerFlags().Center().Border(wxALL));

    m_dirPicker = new wxDirPickerCtrl(this, wxID_ANY, wxEmptyString,  wxDirSelectorPromptStr);
    m_dirPicker->SetMinSize(wxSize(250, -1));
    flex_grid_sizer->Add(m_dirPicker, wxSizerFlags().Border(wxALL));

    auto stdBtn = CreateStdDialogButtonSizer(wxOK|wxCANCEL);
    dlg_sizer->Add(CreateSeparatedSizer(stdBtn), wxSizerFlags().Expand().Border(wxALL));

    SetSizerAndFit(dlg_sizer);
    Centre(wxBOTH);

    // Event handlers
    Bind(wxEVT_INIT_DIALOG,
        [this](wxInitDialogEvent& event)
        { 
            m_dirPicker->SetPath(wxFileName::GetCwd());
            m_filePicker->SetInitialDirectory(wxFileName::GetCwd());
            event.Skip();
        } );

    return true;
}
