////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor ( https://github.com/KeyWorksRW/wxUiEditor/ )
//
// DO NOT EDIT THIS FILE! Your changes will be lost if it is re-generated!
////////////////////////////////////////////////////////////////////////////

#pragma once

#include <wx/dialog.h>
#include <wx/event.h>
#include <wx/filepicker.h>
#include <wx/gdicmn.h>
#include <wx/notebook.h>
#include <wx/stattext.h>
#include <wx/string.h>

class OptionsDlgBase : public wxDialog
{
public:
	OptionsDlgBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = "Options for .srcfiles",
		const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize,
		long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER);

protected:
	wxString m_ProjectName;
	bool m_isWindow { false };
	bool m_isConsole { false };
	bool m_isLibrary { false };
	bool m_isDll { false };
	bool m_isSpaceOptimization { true };
	bool m_isSpeedOptimization { false };
	wxString m_IncludeDirs;
	wxString m_CommonCppFlags;
	wxString m_ReleaseCppFlags;
	wxString m_DebugCppFlags;
	wxString m_CommonLibs;
	wxString m_ReleaseLibs;
	wxString m_DebugLibs;
	wxString m_BuildLibs;
	wxString m_commonRcFlags;
	wxString m_releaseRcFlags;
	wxString m_debugRcFlags;
	wxString m_commonClangFlags;
	wxString m_releaseClangFlags;
	wxString m_debugClangFlags;
	bool m_useMSLinker { false };
	wxString m_commonMidlFlags;
	wxString m_releaseMidlFlags;
	wxString m_debugMidlFlags;

	wxNotebook* m_notebook;
	wxStaticText* m_staticText;
	wxDirPickerCtrl* m_TargetDirPicker;
	wxFilePickerCtrl* m_PchHeaderPicker;
	wxFilePickerCtrl* m_PchSrcPicker;

	// Virtual event handlers, overide them in your derived class
	virtual void OnAddIncDir(wxCommandEvent& event) { event.Skip(); }
	virtual void OnAddCommonLibraries(wxCommandEvent& event) { event.Skip(); }
	virtual void OnAddReleaseLibraries(wxCommandEvent& event) { event.Skip(); }
	virtual void OnAddDebugLibraries(wxCommandEvent& event) { event.Skip(); }
	virtual void OnAddBuildLibraries(wxCommandEvent& event) { event.Skip(); }

private:
};
