# Generated by wxUiEditor -- see https://github.com/KeyWorksRW/wxUiEditor/
#
# DO NOT EDIT THIS FILE! Your changes will be lost if it is re-generated!

set (wxue_generated_code

    ${CMAKE_CURRENT_LIST_DIR}/convertdlgBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/convertvs_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/optionsdlgBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/vscodedlgBase.cpp

)
