# Requires MakeNinja version 1.0.0 or higher to process

Options:
    Project:     MakeNinja    # project name
    exe_type:    console      # [window | console | lib | dll]
    PCH:         pch.h        # "none" or name of header file to use for precompilation

    64Bit:       true         # generate scripts for 64-bit build
    TargetDir64: ../bin64     # 64-bit target directory
    32Bit:       true         # generate scripts for 64-bit build
    TargetDir32: ../bin32     # 64-bit target directory

    IncDirs:     ../ttLib/include                  # additional directories for header files
    BuildLibs:   ../ttLib   # libraries that need to be built (added to makefile generation)

    Natvis:      makeninja.natvis                  # MSVC Debug visualizer

Files:
    makeninja.rc        # Windows resource files
    mainapp.cpp         # entry point, global strings, library pragmas

    addfiles.cpp        # Used to add one or more filenames to a .srcfiles file
    codelite.cpp        # Creates a CodeLite project
    convertdlg.cpp      # CConvertDlg for converting a project into a .srcfiles
    cmplrClang.cpp      # Creates .ninja scripts for CLANG and GCC compilers
    cmplrMsvc.cpp       # Creates .ninja scripts for MSVC and CLANG-CL compilers
    createmakefile.cpp  # CreateMakeFile method for creating a makefile
    csrcfiles.cpp       # CSrcFiles class for reading .srcfiles
    dryrun.cpp          # CDryRun class for testing
    finder.cpp          # Routines for finding executables such as the MSVC compiler
    gencmdfiles.cpp     # Generates MSVCenv.cmd and Code.cmd files
    ninja.cpp           # CNinja for creating .ninja scripts
    options.cpp         # contains all Options strings and CSrcOptions class for working with them
    parsehhp.cpp        # CParseHHP class for parsing a .hhp file
    NinjaStringIds.cpp  # Maps IDS_ strings into string to translate
    rcdep.cpp           # Contains functions for parsing RC dependencies
    vcxproj.cpp         # Creates a Visual Studio project file
    verninja.cpp        # CVerMakeNinja class
    vscode.cpp          # Creates/updates .vscode files
    writesrcfiles.cpp   # CWriteSrcFiles class for writing .srcfiles
    yamalize.cpp        # Used to convert .srcfiles to .vscode/srcfiles.yaml

# Modules for creating the Options UI

    dlgoptions.cpp      # CTabOptions dialog

    tabgeneral.cpp
    tabcompiler.cpp
    tabclang.cpp
    tablinker.cpp
    tabrcmidl.cpp

    addfuncname.cpp     # CAddFuncName dialog
    dlggettext.cpp      # CDlgGetText dialog
