# Requires ttBld.exe version 1.4.0 or higher to process

Options:
    Project:     ttBld        # Target name ('D' will be appended to Debug builds, e.g. ttBldD.exe)
    Exe_type:    console      # [window | console | lib | dll]
    Pch:         pch.h        # "none" or name of header file to use for precompilation
    Optimize:    space        # [space | speed] optimization
    Warn:        4            # [1-4]
    Crt_rel:     dll          # [static | dll] type of CRT to link to in release builds
    Crt_dbg:     dll          # [static | dll] type of CRT to link to in debug builds
    Ms_linker:   false        # true means use link.exe even when compiling with clang

    CFlags_cmn: -std:c++17 /Zc:__cplusplus  # flags to pass to the compiler in all builds

    TargetDir: ../bin         # 64-bit target directory

    Natvis:      ../winsrc/ttBld.natvis # MSVC Debug visualizer

    IncDirs:     precompile;../ttlib/include  # temporary location, change before Public release
    BuildLibs:   ../ttLib/winsrc              # temporary location, change before Public release

Files:
    ttBld.rc
    mainapp.cpp

    cmplrMsvc.cpp       # Creates .ninja scripts for MSVC and CLANG-CL compilers
    createmakefile.cpp  # Creates an MS nmake and GNU-make compatible makefile
    csrcfiles.cpp       # CSrcFiles class for reading .srcfiles
    dryrun.cpp          # CDryRun class for testing
    ninja.cpp           # CNinja for creating .ninja scripts
    options.cpp         # contains all Options strings and CSrcOptions class for working with them
    rcdep.cpp           # Contains functions for parsing RC dependencies
    verninja.cpp        # CVerMakeNinja class
