name: clang-format verifier

on:
  push:
    branches:
      - main
    paths-ignore:
      - src/archive
      - src/art
      - src/xml
      - src/pugixml
      - ttLib
      - tests

  pull_request:
    paths-ignore:
      - src/archive
      - src/art
      - src/xml
      - src/pugixml
      - ttLib
      - tests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.12
      with:
        source: './src'
        exclude: file
        extensions: 'h,cpp'
        clangFormatVersion: 12
        style: file
